n: integer;
m: integer = 20;
b: boolean;
c: boolean = true;
s: string;
t: string = "hello\n";
d: char;
e: char = 'x';
x: array [] string;
y: array [] string = {0};
z: array [] array [] string = {0};
g: array [3] string;
h: array [3] string = {0};
i: array [2] array [3] string = {0};
